type Login {
  status: Int!
  message: String!
  token: Any
}

type Query {
  login(email: Email!, password: Password!): Login!
}

type Mutation {
  register(
    username: String!
    email: Email!
    avatar_url: Image!
    password: Password!
  ): Response!
}
